xen-bugtool

Create a log file to be included in the status report
Log file consists of the parameters of the script, the PATH environment variable and any omitted files
Example output:
```
[root@xenserver-nxmrazyx ~]# cat bug-report-20230713153644/xen-bugtool.log
/usr/sbin/xen-bugtool -a -y
PATH=/opt/xensource/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
Omitting /dev/shm/metrics/xcp-rrdd-xenpm, size constraint of xcp-rrdd-plugins exceeded
Omitting /dev/shm/metrics/xcp-rrdd-mem_vms, size constraint of xcp-rrdd-plugins exceeded
Omitting /dev/shm/metrics/xcp-rrdd-mem_host, size constraint of xcp-rrdd-plugins exceeded
[root@xenserver-nxmrazyx ~]#
```

CP-41107: Store bug tool log in status report

---

.github/workflows/main.yml
.pylintrc

This enables `pylint`'s checks to detect Python2 to Python3 migration problems
in CI using python2 `pylint`'s specific python3 migration checks.
Note: Those had been deemed obsolete and removed in the later `python3 pylint`,
so they only exist in the specific older pylint which runs on and still supports python2 code.
Also add the needed `.pylintrc` for `python2 pylint --py3k` checks.

Add .github/workflows/main.yml to run python2 pylint --py3k checks

---

tests/integration/dom0-template/etc/systemd/system.conf
tests/integration/xenserver-config-systemd.sh

Add the trivial remaining verification that /etc/systemd is indeed _**moved as required by CP-45506**_ to the tarball (the tarball is already checked, but also no files in /etc/systemd/ may remain there, everything must be in the tarball).

CP-45506: Verify that /etc/systemd does not have files(moved to tarball)

---

tests/integration/sar-file-collection.test.sh
xen-bugtool

CA-383852: Fix a recently added feature:
Fix '`sar -A`' from timing out:
> The problem it solves was/is that the attempt to add the output of `sar -A`
> (submitted from outside our team, just reviewed and merged by us) didn't work.
>
> It appeared to work at back then, but when we test it now, we see that it timeouts.
>
> This issue was that when the human-readable output of `sar -A`
> was added in April to `--entries=xenserver-logs`, no timeout
> for this capability was added, and the default timeout is -1:
>
> This results in a nearly immediate timeout of any added command,
> when the capability does is not defined with a specific `max_time=` parameter
> - should we fix this?
To fix this, the reporter of the issue suggested that `sar` (a system load report) could be moved to a new …

CA-383852: Fix output from `sar -A`, move `sar` to `cap(system-load)`

---

pyproject.toml
setup.cfg
xen-bugtool

This the the 1st PR to migrate to Python3:
Start off with a defined config and as most imports will have to be updated,
support the imports to be placed using `isort` at the expected place.
Changes:
- Add .pyproject.toml with configuration for isort and line length
- Add setup.cfg, enable `pip install .` with setuptools_scm
- Apply an initial isort to prepare upcoming imports using isort.

CP-41819: Start py3 migration with config for isort and apply isort

---

xen-bugtool

TLDR: I expect a review of this PR to take maybe 2-3 minutes or so, it's really short and easy:
The only change that is only obvious by reviewing each commit by commit is this change:
```py
if k in ['-d', '--debug']:
dbg = True
+      logging.getLogger().setLevel(logging.DEBUG)  # Activates logging.debug("log messages")
...
From:
-   if dbg:
-      print(...., file=sys.stderr)
-      for (...):
-          print(...., file=sys.stderr)
To:
+   debug(....)
+   for (...):
+       debug(....)   # (Logging default to stderr)
```
It should be clear - if not preferred, I can remove the last one or two commits.
<hr>
2nd Pull request for the Python3 migration of xenserver-status-report:
- Updates the except and print() syntax to support Python3
- Updates the prints to `stderr` to use `logging` or …

CP-41819: Update except and print() syntax to Python3, use logging

---

xen-bugtool

Apply a reviewed and fully automated fixup from the 2to3 tool:
- Apply: `2to3 -w -f has_key`:
- Use: `x in y` (or `x not in y`)
- Commit: https://github.com/xenserver/status-report/commit/13556ad3bb8d52b720db43ebc035f795cb41e00b

Fix has_key() for Python3.x: Apply "2to3 -w -f has_key" - Use: x (not) in y

---

xen-bugtool

Two short and trivial updates for Python 3.x (to get these out of the way):
1. [Use hashlib.md5 (2.7 and py3) as md5_new()](https://github.com/xenserver/status-report/commit/c53c2aaea781ae7d8081d52c46683495c19ccbb3)
2. [Skip monkey-patching ZipFile on py3.7+ (has the fix)](https://github.com/xenserver/status-report/commit/00ff7a992b2761e26629cbdc685dfb25242925d6)
- With link to the fix PR for reference:
- https://github.com/python/cpython/pull/12628

Use hashlib.md5 and skip monkeypatching ZipFile for 3.7+

---

xen-bugtool

Update a `map()` in `make_inventory()` to also work with Python3 (using a for loop - more readable and concise):
The syntax for `tuple` parameters in `lambda` functions has been removed in Python3 and must be replaced:
<hr>
This code iterates over the inventory dictionary using the items() method and unpacks each key-value pair into k and v. Then, it calls the inventory_entry() function with the appropriate arguments.
In general, map() is useful when you want to apply a function to every item of an iterable and return a list of the results.
However, if you only need to iterate over the items of an iterable and perform some operation on each item, a for loop is often more readable and concise than using map().
<hr>
Established for Python3 migration with a recent Python3 merge for …

xen-bugtool/make_inventory(): Py3: Update tuple lambda to for loop

---

xen-bugtool

Collect 4 files for SNMP:
/etc/snmp/snmp.xs.conf
/etc/snmp/snmpd.xs.conf
/var/lib/net-snmp/snmpd.conf
/etc/sysconfig/snmpd

CP-44440: Collect config and logs in bugreport

---

.github/workflows/main.yml
.pre-commit-config.yaml
.pylintrc
pyproject.toml
tests/integration/conftest.py
tests/integration/namespace_container.py
tests/integration/utils.py
tests/mocks/xen/lowlevel/xc/__init__.py
tests/unit/test_xapidb_filter.py
xen-bugtool

Add pre-commit to run in the GitHub Workflow on each push and PR update:
Many Python packages use the `pre-commit` Python Framework for sanity checks when updating Python projects.
Additionally, you can run it locally for faster fixing of issues using:
```sh
$ pip3 install pre-commit
$ pre-commit run
```
The most popular checks are:
- Don't commit to the master branch (only commit to private branches)
- Fix not adding trailing spaces to commits
- Fix terminating files with one trailing newline(and not more)
- Fix using conistent LF for line-endings, not a mix with CR/LF.
- Remove unused variables and unused imports and sort imports
- Apply consistent code formatting for the project (using black)
- Check that debug statements are not accitendially merged
- Check that executables have …

Run pre-commit checks in CI (including the Xen-Bugtool Test Environment)

---

tests/integration/test_system_load.py
tests/integration/test_xenserver_config.py
tests/integration/utils.py

Improve integration tests:
Three small commits with to improve verifying the bugtool output and add a testcase:
1. [Improve verifying the expected bugtool output with the dom0 template files](https://github.com/xenserver/status-report/commit/e687eaad7ced3b82bf79a1b7d768ce2d72fe1893)
2. [integration/utils.py: rename function to assert_... like assert_cmd()](https://github.com/xenserver/status-report/commit/723218e34ab63647a976776a8911b49fdbe938a8)
3. [Add tests/integration/test_system_load.py to assert sar output](https://github.com/xenserver/status-report/commit/61b87bcab4baffc2378573e8b8c63c606c59249c)

Add system load testcase to check collecting sar output, improve verification code

---

tests/unit/conftest.py
tests/unit/test_xapidb_filter.py

Summary for @GeraldEV (or other reviewers): This PR:
- It moves existing code to make it commonly usable.
- It adds support for executing the tests with the newer Python3 builds provided in GitHub actions
- It is tested in GitHub CI
Converts the existing `pytest` fixture to test functions of `xen-bugtool` to a common pytest fixtures:
- Moves the `bugtool` test fixture from the existing test case into `pytest`'s `conftest.py` to make it available for all unit tests which need to test `bugtool` functions for updating them to support Python3.
- To support using the test fixture with newer Python versions, add modern import loader using `importlib`.
The Python3 migration of `xen-bugtool` is really tricky (PRs will be documented, details then for each one):
This test fixture will be used by …

tests/unit/conftest.py: Add a common pytest fixture to test functions of xen-bugtool

---

tests/integration/utils.py

pytest framework: add checking the exit code of test commands

pytest framework: add checking the exit code of test commands

---

tests/integration/dom0-template/usr/sbin/mdadm
tests/unit/test_mdadm_arrays.py

`tests/unit/test_mdadm_arrays.py`: add test for `mdadm_arrays()`
Assert `mdadm_arrays()` returning the `/dev/md` arrays of the `mdadm` mockup in the `dom0-template`.

tests/unit/test_mdadm_arrays.py: add test for mdadm_arrays()

---

tests/unit/test_xapidb_filter.py

xen-bugtool's DBFilter class filters secrets from the XAPI database.
The test case [tests/unit/test_xapidb_filter.py](https://github.com/xenserver/status-report/pull/30/files#diff-e72d2129c2694911731f812f6454629fa8ec8b049b7659d3ad9417eb9da6a097) verifies that the `DBFilter` does the filtering of secrets correctly.
Initially, it asserted it using:
```py
assert xml.dom.minidom.parseString(filtered).toprettyxml(indent="    ") == expected
```
When used for Python3, the result of the `parseString(filtered).toprettyxml()` does not produce the same output, but the only difference is that it orders the attribute `id` as the first attribute.
This PR extends the test case to have an additional verification that works the same for Python2 and also is able to assert that the function still works in …

tests/unit/test_xapidb_filter.py: Update/Prepare testcase for Python3

---

tests/unit/test_dir_list.py

Add `tests/unit/test_dir_list.py`: Unit-Test `bugtool.dir_list(cap, path_list)`
Test-driven Python3:
I let the needed unit tests run with Python2 before making "deep" changes for Python3 to the code (which will be needed) to create test coverage for the changes and prevent bugs/regressions.

Test the bugtool function dir_list(cap, path_list) to perform as expected

---

tests/integration/conftest.py

Fix the typos that I missed when creating the namespace container for tests.

Fix typos in comments

---

tests/integration/conftest.py

Rename the variable `srcdir` to `src_dir` to fix spelling checks, which also makes it easier on the eye.

Rename the srcdir variable to fix spelling checks

---

.coveragerc
.github/workflows/main.yml
.pre-commit-config.yaml
tests/integration/conftest.py
tests/integration/namespace_container.py
tests/integration/utils.py
tests/unit/conftest.py
tests/unit/test_xapidb_filter.py
xen-bugtool

Collect, check and report code coverage from Python3 unit test runs:
- Add `.coveragerc` and mark not covered branches
- Collect and check minium and diff code coverage in pre-commit
- For GitHub CI:
- Add the Pytest Coverage Comment action, it shows:
- Number of Python3 pytest tests executed, skipped, failures, errors and duration
- When the title above the table is expanded:
- The complete list of all not covered lines from the Python3 test run is shown
- These reported lines have links to the source code
- Add coverage upload to https://codecov.io, which once merged:
- Provide a link to Codecov code coverage analysis, with the changes to the coverage
- The Codecov comment will report if all changes lines are not covered by the unit test.
Sample of how such Codecov comment will look …

CP-41819: Py3: Collect, check and report code coverage from Python3 unit test runs

---

Makefile

pre-commit: When formatting staged changes for xen-bugtool, don't normalize string quotes to " for now.

pre-commit: Don't string-normalize quotes in xen-bugtool for now

---

xen-bugtool

The fixed line caused a TypeError Exception when a pid disappeared:
- The argument "d" is a pid from os.listdir('/proc'),
- but it is a string, not an int.
- Also, it does not need to be passed as the first element in a set.

Bugfix: xen-bugtool/fd_usage(): Fix TypeError when a pid disappears

---

tests/unit/test_fs_funcs.py
xen-bugtool

Remove not used function prettyDict()
- It is unused since 2012
- The bugtool script does not import external code such as Python plugins
- Hence, it is really unused -> remove.

Remove not used function prettyDict()

---

xen-bugtool

Note on the test for this change:
The change in this PR is covered by two different container-based tests.
These are not unit tests, but tests which run bugtool as an external process in a container and ensure that the requested functionality is not broken by checking that /etc/systemd is still archived into a tarball inside the main bugball.
These are the links to the two lines (one for tar output archives, one for zip output archives) in the simple shell script based test (which runs inside a container) that extracts and later verifies the contents of the /etc/systemd.tar tarball in the output archive:
https://github.com/xenserver/status-report/actions/runs/7500658225/job/20419801112?pr=48#step:7:26
https://github.com/xenserver/status-report/actions/runs/7500658225/job/20419801112?pr=48# …

CP-45506: Fix asking if /etc/systemd/* should be collected

---

.pylintrc
tests/unit/test_main.py
xen-bugtool

When status-report was executed using --debug and --entries=, and one of the entries was not known, it terminated with an error in a debug message (after it had already written the output archive).
Fix this by logging a warning for the unknown option.

'Debug: Fix abort in debug mode on unknown entries'

---

tests/unit/test_output.py
xen-bugtool

Fix harmless warning: Close sub-archives without members:
- Fix the python (from developer mode) about not closing a sub-archive if it has got no members.
- Cover the new lines by a tiny unit test improvement.
This is based on #45 (the 1st commit) as it needs its improved coverage for unit tests to pass.

Fix harmless warning: Close sub-archives without members as well

---

tests/unit/test_main.py

CI: Add new test to cover lines handling unknown command line options
- Covering the lines which handle unknown command line options is needed in preparation for upcoming changes where the code coverage appears to be behaving strangely.
- And of course it raises the code coverage a little more.

CI: Add new test to cover lines handling unkown command line options

---

tests/integration/utils.py

Improve the developer experience when files do no show up in the bugball output archive and the associated test fails.

CI/utils.py: Better diagnostic output when tests fail

---

.github/workflows/Python-problemMatcher-status-report.json
.github/workflows/main.yml

Minor fix for GibHub problem matching:
GitHub CI: Fix problemMatcher file to match status-report paths
It's really tiny and from what I saw in a xen-api PR where I added it the same way, this will enable GitHub to annotate the source code when PYTHONWARNINGS are issued by the Python interpreter (e.g. it will show warnings about regexes that are deprecated or invalid, not closed files from unit test runs etc)
* This should help GitHub to show annotations in the PR review in case python tests show a warning in the GitHub CI workflow output.

GitHub CI: Fix problemMatcher to match status-report paths

---

xen-bugtool

This is one-line revert of a change that I made for CP-45506 (Mea-culpa) that turned out to not be needed for it and turned out to change the interactive mode (when `--yes-to-all` | `-y`) is not given. In this case, interactive "`n`" answers for not collecting files in /etc/systemd to be ignored when `xenserver-status-report` is run interactively:
> For CP-45506 (Package /etc/systemd into a tarball), I had assumed that it would be needed to move the tree_output() for /etc/systemd to after where the tarball for /etc/systemd is declared, but this was not needed.
>
>Moving it had the side effect that in interactive mode (a question if each individual file shall be collected - lots of of questions), the /etc/systemd tarball was simply always collected.
>
> This commit fixes this by reverting …

Backport CP-45506: Honor "n" on files in /etc/systemd/ in interactive mode

---

.github/workflows/main.yml

This PR fixes a few GitHub CI warnings, mostly because GitHub plans to remove Node16 this Spring...
It updates `.github/workflows/main.yml`, with these minor updates to fix all GitHub warning annotations that can be fixed at the moment:
- Limit actions which only work in pull_request runs to only run in pull requests
- Do not upload to codecov.io only from pull_request runs: The updated action failed to upload to Codecov.io for commits in a forked repo. If a developer wants coverage uploads, a PR needs to be created.
- All GitHub actions now issue a warning that they are deprecated - upgrade those that we can update:
https://github.com/xenserver/status-report/actions/runs/7801223710
----
Justification given by GitHub for removing node16 actions:
> Node 16 has reached its [end of …

GitHub CI: Fix warnings from deprecated Node16 actions: Update them

---

tests/integration/dom0-template/usr/sbin/xenstore-ls
tests/unit/test_main.py
tests/unit/test_xapidb_filter.py

Code coverage: cover both branches of filter_xenstore_secrets()
@ashwin9390 found that due to CA-136105 and CA-198975, clipboard data may no longer be in the output of `xenstore-ls -f`, (and also not in xenstored-access.log - it only seems to have the `set_clipboard` and `report_cliboard` events but no data).
If this is true, we may be able to remove the `filter_xenstore_secrets()` as the filter function for `xenstore-ls -f`, but to be safe, I'd like to get two competent confirmations/approvals for the removal of the filter.

Code coverage: cover both branches of filter_xenstore_secrets()

---

pytest.ini
tests/unit/conftest.py
tests/unit/test_filter_xapi_clusterd_db.py
xen-bugtool

Fix filtering the XAPI Clustder DB as found by CA-388587 (found using testing by @ashwin9390)
- Commit 1 and 1 setup unit testing:
- Commit 1 enables enforced version of:
1. Create a test and make it fail
- Use Strict XFAIL only: An unexpected PASS is fail.
2. Then fix the code.
3. And remove the XFAIL marker at the same time (the strict XFAIL setting forces you to remove it) 
- The Fix 1 and Fix 2 commits reuse original patches by @edwintorok for this issue.
- They fix the bugs and remove their respective XFAIL marker.
- Fix 3 applies the lesson learnt:
- to log errors during processing to the bug-tool logfile for analysis.
The tests that are created and fixed as described in the module docstring of the test case module.

CA-388587: Fix filtering the `xapi-clusterd` `db` and log any errors

---

tests/unit/test_filter_xapi_clusterd_db.py
xen-bugtool

CA-358870: Backport the fixes to filter the XAPI Clusterd DB for XS8, Yangtze:
Fixes for `filter_xapi_clusterd_db():`
1. Remove the clusterd token (backport of @edwintorok's patch)
(cherry picked from #67, 9a64b448d4431ebe228652421ef4e80131e95bb1)
3. Fix `KeyError` if `pems` and `authkey` don't exist in DB (backport of @edwintorok's patch)
(cherry picked from #67, e4a80b6e7f433ed72cce0045eb240d112fd73e78)
2. Log any errors in filter_xapi_clusterd_db()
If Exceptions would occur in the future, log them to the bugtool log (with testcase for it)
(cherry picked from #67, 5fd22f80f7f21a675e70454db4b12089620320fd)

CA-358870: Backport the fixes from #67 to filter the XAPI ClusterD DB for XS8, Yangtze

---

tests/unit/conftest.py

This only changes the refactors file `tests/units/conftest.py`
- it is the local `pytest` fixtures for this directory
- and the changes do not break the tests in any way. 
For a clean review, I refactored the Refactoring part from #67 into the PR.
It follows the TDD model of
- Add failing test
- Fix the code and switch the test to pass
- Refactor (this PR - but these are only cosmetic updates) <---------------------------
Everything here already has 100.00% code coverage (the every file in `tests/unit/*` is 100.00% covered)
It is split into two commits, the 1st for actual refactoring:
- nothing is moved
- just tiny improvements from review comments
And the 2nd commit is only comments and `docstring` clean-up to shorten them - doc is n #68.
-----
- This PR contains two overlapping commits …

Cosmetic clean-up of the `pytest` fixtures in tests/unit/conftest.py

---

.pylintrc.project-dict.txt
tests/unit/conftest-README.md

Docs-only: 
- `tests/unit/conftest-README.md`: Add README documenting tests/unit/conftest.py
- This is the direct link to the new README.md like you want to read it (Markdown-formatted):
https://github.com/xenserver-next/status-report/blob/add-tests-unit-conftest-README.md/tests/unit/conftest-README.md
- Also adds a local project dictionary which enables spellchecking code and documentation.

Docs-only: Add tests/unit/conftest-README.md documenting tests/unit/conftest.py

---

README-pytest-chroot.md

Clean-up README-pytest-chroot.md to 88 column width.
Also removed a bit of superfluous verbosity that did not tell something.

Clean-up README-pytest-chroot.md to 88 column width

---

tests/unit/test_fs_funcs.py
xen-bugtool

Fix the test of `disk_list()` to be host/OS-independent and test also the major device number filter in it:
- the 1st commit only prepares the code for the new test and the tested return value does not change in GitHub CI.
- the 2nd commit then updates the test to be a proper test, checking the branches in the function to perform as expected (e.g. devices with major device id >= 245 are filtered out)
In short, the commits are:
1. Update xen-bugtool.disk_list() to use the existing PROC_PARTITIONS variable (and also use `with open()`)
2. Update the test case to supply much better test data showing the filtering that the function is implemented to do to work.

Fix test for `disk_list()` to be OS-agnostic and test the major device number filter

---

.github/workflows/main.yml

Two commits here:
- they don't overlap the same lines
- They make their change twice because we upload coverage with the python2.7 and python3.<whatever version> to coverage databases (coverity.io / coveralls.io)
- they only alternate within the same file 
The commits are:
- [CodeCov: Use the CLI if the token is set, else the legacy action](https://github.com/xenserver/status-report/commit/3d8245db0d4fb523d4f974530c9cebed219fe2ce)
- restores coverage upload to coverity:
- the new uploaded needs the Codecov Upload Token that isn't set up yet, restores coverity upload
- Upload to Coverity is fixed, but does not show the coverage because the fork-point of this PR had no working coverage upload to compare coverage against.
- [Coveralls: Add coverage upload to …

Restore coverage upload to codecov (falls back to legacy uploader), add coveralls upload

---

tests/integration/conftest.py
tests/integration/namespace_container.py
tests/integration/test_system_load.py
tests/integration/test_xenserver_config.py
tests/integration/utils.py

Use the Commits tab to review the fix for the integration test independent of the formatting changes in commit #2
- [Fix integration test to use python2+3](https://github.com/xenserver/status-report/commit/2b018d07733686c4f0782e10ecd72fd61a32dc1f)
- I also added the clean-up of a logging print() in the test that is not that much needed here.
- [Improve readability of the code, limit to 88 columns](https://github.com/xenserver/status-report/commit/acded429336a1e3453ce82884061d0994f73da08)
- This does not change code in any way, it only improves the comments not exceed 88 colums.
PS: At some later point, black will do the remaining work with (code with 88 columns is more readable):
```py
[tool.black]
- line-length = 108
+ line-length = 88
```

Improve readablity of integration tests

---

xen-bugtool

StringIOmtime is used by many functions:
Currently it is located at the end of the file just above main(). This is not the correct place for it.
Move it up to the utiltiy fuctions to define it before using it
Rationale: Moving the function fixed warnings on the function not behind defined before use in VSCode.
Also, and more importantly, moving it is consistent with the general function order where the low-level functions and classes like this one are first and then the "business" logic that uses these low-level functions.

StringIOmtime: move it to define it before using it

---

tests/unit/test_main.py
xen-bugtool

Python2 `input()` is eqivalent to: `eval(raw_input())`, which was wrong for Python2. Fix it.
For reading input lines like `y` (without "quotes") from stdin, we need to use `raw_input()` on Python2.
AshwinH contributed this comment in his approval:
Documentation for this change :https://codeql.github.com/codeql-query-help/python/py-use-of-input/

Fix yes/no input for Python2/XS8: revert to raw_input() on Python2

---

.pre-commit-config.yaml
requirements-dev.txt
tests/unit/conftest.py
tests/unit/test_dump_xapi_procs.py

Add a unit-test for `dump_xapi_subprocess_info()` which covers all lines of the function:
https://app.codecov.io/gh/xenserver/status-report/pull/85/indirect-changes

CP-48196: Add a unit-test for `dump_xapi_subprocess_info()`

---

.github/workflows/check_branch-needs-rebase.py
.github/workflows/main.yml
.pre-commit-config.yaml
.vscode/ltex.dictionary.en-US.txt

Add pre-commit hook to check if the current branch needs rebase
- GitHub runs CI on the PR branch rebased to the target branch if possible.
- To avoid hard side effects from working on the branch that is behind the target, warn about it.

Add pre-commit hook to check if the current branch needs rebase

---

.pre-commit-config.yaml
xen-bugtool

This is part of CA-357771 | Cleanup StorageLink / CVSM leftovers in bugtool and console
Clarified with Mark Syms:
> they were removed in XenServer 6.5
Thus, we can go ahead and remove the CVSM / csl_logs code.
This obsoletes the need to test the Python3 changes to it: The dead code is gone for good.

CP-47521: Cleanup CAP_CVSM and StorageLink code (was removed in XS 6.5)

---

tests/unit/test_main.py
xen-bugtool

CA-390127: Fix adding even the last log() messages to the output archive
The merge target of this PR is the same commit as in #92:
The reason for this is that this commit of #92 includes the needed unit test as the basis to verify this fix with an update to the unit test of #92.
Please review #92 as well, and after #92 is merged, I'll change the target of this PR to master (and I'll notify you for a final re-approval then)

CA-390127: Fix adding even the last log() messages to the output archive

---

tests/unit/conftest.py
tests/unit/test_dump_xapi_rrds.py
tests/unit/test_output.py

Python3.12's `mocker.patch()` stopped supporting modules with a `"-"` in them.
Use `"bugtool"` as the module name instead of `"xen-bugtool"` to avoid this problem with the mocker.patch() function in Python 3.12.
The other commit in this PR for the dictionary file is needed to fix the spellcheck in CI.

Fix mocking the `xen-bugtool` script in with Python 3.12 

---

.vscode/ltex.dictionary.en-US.txt
tests/unit/test_main.py
xen-bugtool

@MarkSymsCtx: Updated to try to append and fall back only when seeking to append fails:
```py
try:  # Python3.6 does not support "ab" if the file is not seekable:
binary_fileobj = os.fdopen(output_fd, "ab")
except OSError:  # pragma: no cover
binary_fileobj = os.fdopen(output_fd, "wb")
self.tf = tarfile.open(name=None, mode="w|", fileobj=binary_fileobj)
```
----
When running this command on a real XS8 Dom0, this error occurs:
```py
PYTHONPATH=tests/mocks /usr/bin/python3 ./xen-bugtool --output=tar --outfd=1 -sy|tar tvf -
Traceback (most recent call last):
File "./xen-bugtool", line 2358, in <module>
sys.exit(main())
File "./xen-bugtool", line 1290, in main
archive = TarOutput(subdir, output_type, output_fd)
File "./xen-bugtool", line 1886, in __init__
self.tf = tarfile.open(None, 'w|', …
```

CP-48444: Fix crash of Python3.6 with "Illegal seek" with --outfd

---

.vscode/ltex.dictionary.en-US.txt
tests/unit/test_main.py
tests/unit/test_output.py
xen-bugtool

Fix adding even the last log() messages to the output archive
- In the test added (extended) for CP-48447 (below) which extends test_main.py (which calls `xen-bugtool.main()`), the exception raised and logged as part of the test execution could not be found in the `xen-bugtool.log` file that is recorded in the `bugtool` output archive.
- However, the exception was shown to be included in the `xen-bugtool.log` file itself (not in the output archive)
- The reason for this behaviour was that `xen-bugtool.log` was collected before the exception was written to it:
- Because there is no guarantee that this file is collected last, update it to be explicitly collected at the end of processing before generating the inventory.xml and closing the archive.
- This was already approved by @GeraldEV in …

CP-48447+CA-390127: correct exception handling for func_output callbacks, fix saving all log messages

---

xen-bugtool

CA-390129: Handle & log exceptions in `dump_xapi_rrds()` from `xen-bugtool --entries=persistent-stats`:
While this capability is hidden, is executed when `xen-bugtool -y -a` is called.

CA-390129: Handle & log exceptions in dump_xapi_rrds(hidden and disabled)

---

.pre-commit-config.yaml
tests/unit/test_dump_xapi_rrds.py

This new test confirms that `log_exceptions()` (added with #94) logs exception messages to the collected xen-bugtool.log file and to stdout.
This PR also has a 2nd commit with a note on how to best skip a pre-commit check for rebasing the PR branch:
- As an exception from the norm of "one PR, one topic", I think that adding this 2nd commit here is fine because both are very small changes, and we don't need a separate PR just to add a hint for developers.

CA-390129: Add the unit test case for the exception handler added in #94

---

.coveragerc
.github/workflows/main.yml
.pre-commit-config.yaml
.vscode/ltex.dictionary.en-US.txt
README.md
pyproject.toml
pytest.ini
sonar-project.properties
tests/integration/test_system_load.py
tests/integration/test_xenserver_config.py
tests/integration/utils.py
tests/unit/conftest.py
tests/unit/test_main.py
tests/unit/test_output.py
xen-bugtool

Optionally allow repos to use Sonar to manage clean code and fix Sonar warnings
- Fix warnings from sonarlint and Sourcery
- Update configuration to be compatible with sonarcloud
- When the SONAR_TOKEN variable is added to a repo, sonarcloud can help to review pull requests. 
- It can (optionally) add a pull request comment that looks like this:
----
Issues
- [0 New issues](https://sonarcloud.io/project/issues?id=xenserver-next_status-report&pullRequest=26&resolved=false&inNewCodePeriod=true)
- [0 Accepted issues](https://sonarcloud.io/component_measures?id=xenserver-next_status-report&pullRequest=26&metric=new_accepted_issues&view=list)
(Remark for the PR: Accepted issues are like "WONTFIX" (acknowledged, but decided to not fix)
Measures
- [0 Security …

Allow repos to use Sonar to manage clean code, fix warnings

---

.vscode/ltex.dictionary.en-US.txt
xen-bugtool

While this reverts the removal of PBIS support in the master branch (that master would not need now), it would make sense to apply revert the removal of it in master as well to be able to use the master branch as basis for future hotfixes again like we did for UPD-948 (StatusQuo): One example where it could be decided to do this gain would be syncing of RRDs to disk before capturing them which is planned for 8.2 CU1. It would involve backporting the larger patch of https://github.com/xenserver/status-report/pull/51 which resulted in an issue that needs https://github.com/xenserver/status-report/pull/88. Using master like UPD-948 did would be an option for this future release. But for this to be have no regressions, we should also apply this to master:
XS8 migrated from PowerBroker …

CA-390759: Revert removal of PBIS (PowerBroker Identity Service) for future backports.

---

.github/workflows/main.yml

GitHub CI: Fix Codecov uploads from the merged commits on master

CP-48198: Fix Codecov uploads from the merged commits on master

---

tests/unit/test_filter_xapi_clusterd_db.py

Clean-up too long comments in `tests/unit/test_filter_xapi_clusterd_db.py`:
- Remove comments in the header that are in doc/pre-commit.md now:
see previous PR: #101

CP-48198: docs-only: test_filter_xapi_clusterd_db.py: Clean-up of comment in header

---

doc/pre-commit.md

- doc/pre-commit.md: Minor updates and cleanups

CP-48198: `pre-commit.md`: Minor updates and cleanups

---

tests/unit/test_filter_xapi_clusterd_db.py

Clean-up too long comments in `tests/unit/test_filter_xapi_clusterd_db.py` inside `assert_filter_xapi_clusterd_db()`

CP-48198: docs-only: test_filter_xapi_clusterd_db.py: Clean-up long comments

---

tests/unit/test_filter_xapi_clusterd_db.py

`test_filter_xapi_clusterd_db.py`: Self-test asserting the expected output
The motivation for this PR is that I wanted to confirm that the clusterd secrets are really removed from the collected clusterd database data in the context of the question on another PR were we are looking at the clusterd on whether we can rely on the status-report to really safely filter the secrets in the cluster DB.
To double-check that we can rely on the checks in `test_filter_xapi_clusterd_db.py`, I reviewed them again to ensure that they work as required.
Changes:
- Merges test_pems_blobs() and test_remove_token() into test_removal_of_all_secrets()
- Adds new self-tests:
- `test_assertion_on_unexpected_token()`       (Check assert on token that is not expected)
- `test_assertion_on_unexpected_authkey()` …

CP-48198: test_filter_xapi_clusterd_db.py: Self-test asserting the expected output

---

.coveragerc
.github/workflows/main.yml
tests/conftest.py
tests/integration/conftest.py
tests/integration/test_system_load.py
tests/integration/test_xenserver_config.py
tests/integration/utils.py
tests/unit/conftest.py
tests/unit/test_main.py
tests/unit/test_output.py

- [`.github/workflows/main.yml`](https://github.com/xenserver/status-report/pull/105/files#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3):
- Fix running `tests/integration` in GitHub CI which use `/opt/hostedtoolcache` to provide Python.
- Therefore, `tests/integration` needs to use `/opt/xensource` as mount point for the dom0 template files in `/opt/xensource`.
- [`tests/integration/utils.py`](https://github.com/xenserver/status-report/pull/105/files#diff-d9e46323e51c9f9cfa4c9fa1acc40a8cc931da3ba7f82f6867360507590cc671): Use `runpy.run_path(bugtool_script, run_name="__main__")` to get coverage if the script
- [`tests/integration/conftest.py`](https://github.com/xenserver/status-report/pull/105/files#diff-c87c5173e88bb0f60b00107f4586304f4869a976a4f998425efe3481c0db9 …

CP-48198: Fix running pytest on tests/integration in GitHub CI (with coverage)

---

.github/workflows/main.yml
xen-bugtool

biosdevname opens /dev/mem to read the $PIR PCI interrupt routing table. This fails with Secure Boot enabled and causes a warning in the kernel. log. Since the $PIR PCI interrupt routing table is used for routing PCI interrupts to ISA IRQs, it is not useful on any modern system so pass "-x" to biosdevname to avoid this behaviour.

CA-392459: Avoid opening /dev/mem when calling biosdevname

---

.github/workflows/main.yml
.vscode/ltex.dictionary.en-US.txt
README.md

Because the question comes up from time to time,
add an FAQ on Code complexity relative to Python2 support
PS: The 1st commit to fix coveralls upload is also in #108 to fix GitHub CI. The PR that is merged first needs it, and it will be removed when merging the 2nd PR.

README.md: Add an FAQ on Code compexity relative to Python2 support

---

tests/integration/dom0-template/usr/sbin/modinfo
tests/unit/test_process_output.modules
tests/unit/test_process_output.py
xen-bugtool

Fix CP-49659:
- Test `modinfo` returning non-ASCII characters and
- fix the error triggered by it.
XS8: If these kernel modules are loaded, the bugtool file modinfo.out is broken:
```js
bq2415x_charger bq2415x charger driver
cb710           ENE CB710 memory card reader driver
cb710-mmc       ENE CB710 memory card reader driver
cdc_mbim        USB CDC MBIM host driver              (for MBIM Mobile broadband modems)
dell-smm-hwmon  Dell laptop SMM BIOS hwmon driver     (for Dell Laptops)
gl520sm         GL520SM driver                        (I2C temperature/voltage Sensor)
i2c-via         i2c for Via vt82c586b southbridge     (Via Chipsets)
nf_dup_ipv4     nf_dup_ipv4: Duplicate IPv4 packet
nf_dup_ipv6     nf_dup_ipv6: IPv6 packet duplication
nft_socket      nf_tables socket match module …
```

CP-49659: Test `modinfo` returning non-ASCII characters and fix the triggered error

---

pytest.ini
tests/unit/test_filter_xapi_clusterd_db.py

Update support for testing using pytest:
Add support for pytest-8.2 on Python3.11 (color, verbose)
This change supports the different assertion diagnostic output that pytest-8 produces:
The assertions from pytest-8 include escape sequences for colouring the output nicely, and to pass both, the string that we expect to find in the assertion needs to be shorter.
For pytest v8 to produce the assertion messages that this test expects, we need to add `-vv` to the default pytest options to enable more verbose assertion messages. 
By default, also show the local variables in the traceback of an test exception: Add `--showlocals` to the default options.

pytest: Add support for pytest-8.2 on Python3.11 (color, verbose)

---

.vscode/ltex.dictionary.en-US.txt
tests/integration/dom0-template/etc/xensource/bugtool/mock/stuff.xml
tests/unit/test_load_plugins.py
tests/unit/test_output.py
xen-bugtool

- Fix multiple file patterns for the same directory:
- Append the directory specifications to a list instead of overwriting the previous directory spec.
```py
if path in directory_specifications:
directory_specifications[path].append((cap, pattern, negate))
else:
directory_specifications[path] = [(cap, pattern, negate)]
```
Then, when we loop over the directory_specifications, loop over the list of tree_output_entries:
```py
for directory, tree_output_entries in directory_specs.items():
for directory_items in tree_output_entries:
capability, pattern, negate = directory_items
```
When ignoring shifting the indendation to loop over the tree_output_entries, the change is small:
The output of `git log -w -p -n1 xen-bugtool` of the commit is:
```py
--- a/xen-bugtool
+++ b/xen-bugtool
@@ -602,7 …
```

CA-394409: plugins: Fix multiple file patterns for the same directory

---

.github/workflows/check_branch-needs-rebase.py

Minor update for the `pre-commit` check for need of rebase on push:
- Enable printing of the output messages

Minor update for the pre-commit check for need of rebase: Enable output logging

---

tests/unit/test_output.py
xen-bugtool

This pull request backports a minor improvement from `master` to `release/yangtze`:
It backports a minimal part of https://github.com/xenserver/status-report/pull/33/commits/62601dba1540565431275fbf2efd6e9efb7122c6 from #33 to `release/yangtze`.
This provides the correct base code for backporting the collection of up-to-date RRDs to `release/yangtze` by backporting #51 (and #88, #115, and #82 see below).
Refactor the tests in `test_output.py` by extracting the `include_inventory()` function into a separate definition. 
Additionally, update `tests/unit/test_output.py` to test the `inventory.xml` generated by the extracted function in isolation.
These changes improve the organization, testability and readability of the code.
----
The PR that would be backported based on this PR would be:
- …

Prepare `release/yangtze` for backporting #51 (collect up-to-date RRDs)

---

xen-bugtool

Backport to the Yangtze release branch:
Fix unclosed file objects when tar files are created, like when /etc/systemd.tar is created and collected(systemd units) and when `--output` is used to output to tar files.
This pull request fixes an issue in the TarOutput class where file objects were not being closed properly.
The fix involves using context managers to ensure that the file objects are closed after they are read.
This fix reduces memory usage and may improve the performance of the xen-bugtool / xenserver-status-report process in case tarballs instead of ZIP files are used as output format.

Backport for Yangtze: Fix unclosed file objects in TarOutput

---

xen-bugtool

This is a backport of #119 by @MarkSymsCtx to the Yangtze release branch for the next user-space hotfix for 8.2.1: 
This pull request cherry-picks PR #119 by @MarkSymsCtx for collecting the SCSI disk provisioning mode of SCSI disks.
It collects provisioning mode from the `/sys/block/sd*/device/scsi_disk/*/provisioning_mode` files.
This information is useful for managing and monitoring storage devices.

Yangtze: Cherry-Pick "Add scsi disk provisioning mode" from @MarkSymsCtx

---

xen-bugtool

All initscripts services are migrated to systemd and initscripts family will be removed from dom0.
Just remove `chkconfig --list' from the reporting, and the services status are collecting by `systemctl status`

CP-50546: Remove collecting `chkconfig --list`

---

xen-bugtool

net-tools are legacy, this commit replace it with new ip/ss command as follows:
* ifconfig -a -> ip -s addr
* route -n -> ip route
* arp -n -> ip neighbour
* netstat -anop -> ip -anop
* netstat -s -> ss -s + /proc/net/netstat
* netstat -gn -> ip maddr

CP-51767: Remove net-tools

---

xen-bugtool

Currently when xha logs rotate, the logs rotated over do not get included into the server status report. This makes it difficult to capture and share HA history back to engineering. So add rotated xha logs into the server status report.

CP-52714: Include rolled over xha logs into a server status report

---

xen-bugtool

Fix this issue:
Omitting /etc/systemd/user/dbus.service, size constraint of xenserver-config exceeded Omitting /etc/systemd/user/basic.target.wants/systemd-tmpfiles-setup.service, size constraint of xenserver-config exceeded
Tested: 4243304 NRPE

CA-399631: Increase the max size of xenserver-config for bug-tool

---

xen-bugtool

The status report doesn’t contain rotated yum.log (e.g. yum.log.1, yum.log.2.gz, etc). If the customers have applied multiple updates, the yum.log may be large so that we can’t see rotated yum.log from status report. Also if XenServer has been running over a year, the history yum.log will also be rotated so we can’t get it.

CP-308176: Include rolled yum.log to status report
